# Generated by Django 3.0.5 on 2020-05-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain_home', '0002_auto_20200508_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=999)),
            ],
        ),
    ]
