# Generated by Django 3.0.5 on 2020-05-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captain_home', '0003_slides'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slides',
        ),
    ]
