# Generated by Django 3.0.5 on 2020-05-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captain_home', '0005_auto_20200508_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slides',
        ),
    ]
