# Generated by Django 3.0.5 on 2020-05-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='image',
            field=models.CharField(default='bla.jpg', max_length=999),
        ),
    ]
