# Generated by Django 3.0.5 on 2020-05-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Console_brand_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=999)),
            ],
        ),
    ]
