# Generated by Django 3.0.5 on 2020-05-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_category',
            field=models.CharField(blank=True, choices=[('C', 'Consoles'), ('G', 'Games')], max_length=2),
        ),
    ]
