# Generated by Django 3.0.5 on 2020-05-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20200515_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_category',
            field=models.CharField(blank=True, choices=[('C', 'Console'), ('G', 'Game')], max_length=2),
        ),
    ]
