# Generated by Django 3.0.5 on 2020-05-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20200515_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='testproduct'),
            preserve_default=False,
        ),
    ]
